name: alejo
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - cmake>=3.18
  - dlib>=19.24
  - face_recognition>=1.3.0
  - opencv>=4.8
  - numpy>=1.26
  - scipy>=1.11
  - sounddevice>=0.4.6
  - librosa>=0.10.1
  - tensorflow>=2.15
  - torch>=2.1.0
  - torchaudio>=2.1.0
  - transformers>=4.35.0
  - sentencepiece>=0.2.0
  - scikit-learn>=1.4.0
  - spacy>=3.7.4
  - pip:
    - face-recognition-models>=0.3.0
    - mediapipe>=0.10.8
    - deepface>=0.0.79
    - speechbrain>=0.5.16
    - resemblyzer>=0.1.1
    - pyannote.audio>=3.1.1
    - insightface>=0.7.3
    - pytorch3d>=0.7.5
    - open3d>=0.18.0
    - retinaface>=1.1.1
