[build]
  command = "python -m alejo --build"
  publish = "dist"
  
[build.environment]
  PYTHON_VERSION = "3.9"
  NODE_VERSION = "18.12.0"
  
[dev]
  command = "python -m alejo --dev"
  port = 8888
  publish = "dist"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  
[functions]
  directory = "functions"
