[tool.pytest.ini_options]
minversion = "7.0"
addopts = "-ra -q -v"
testpaths = ["tests"]
python_files = ["test_*.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
asyncio_mode = "strict"
log_cli = false
log_cli_level = "INFO"
