apiVersion: v1
kind: Secret
metadata:
  name: alejo-secrets
  namespace: alejo
type: Opaque
data:
  # These are placeholder values. In production, use proper secret management
  OPENAI_API_KEY: ${OPENAI_API_KEY}
  DB_PASSWORD: ${DB_PASSWORD}
  JWT_SECRET: ${JWT_SECRET}
