name: ALEJO Code Quality

on:
  push:
    branches: [ main, develop ]
    paths-ignore:
      - '**.md'
      - 'docs/**'
  pull_request:
    branches: [ main, develop ]
    paths-ignore:
      - '**.md'
      - 'docs/**'

jobs:
  javascript-lint:
    name: JavaScript Linting
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run ESLint
        run: npx eslint src/**/*.js
        continue-on-error: true
        
      - name: Run Prettier check
        run: npx prettier --check "src/**/*.{js,json,css,html}"
        continue-on-error: true

  python-lint:
    name: Python Linting
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 black isort mypy
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          
      - name: Run flake8
        run: flake8 alejo tests
        continue-on-error: true
        
      - name: Run black
        run: black --check alejo tests
        continue-on-error: true
        
      - name: Run isort
        run: isort --check --profile black alejo tests
        continue-on-error: true
        
      - name: Run mypy
        run: mypy alejo
        continue-on-error: true
        
  typescript-check:
    name: TypeScript Type Check
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run TypeScript check
        run: npx tsc --noEmit
        continue-on-error: true
        
  sonarcloud:
    name: SonarCloud Analysis
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      # Note: The IDE may show a warning about SONAR_TOKEN. This is expected and can be ignored if you're not using SonarCloud.
      # To resolve this warning, add a SONAR_TOKEN secret in your GitHub repository settings:
      #   1. Go to repository Settings > Secrets and variables > Actions > New repository secret
      #   2. Name: SONAR_TOKEN
      #   3. Value: Get token from https://sonarcloud.io/account/security/
      
      # ===== SONARCLOUD CONFIGURATION =====
      # This section is commented out to avoid IDE warnings about SONAR_TOKEN
      # To use SonarCloud, uncomment this section and add the SONAR_TOKEN secret
      # in your GitHub repository settings.
      #
      # - name: SonarCloud Scan
      #   continue-on-error: true
      #   uses: SonarSource/sonarcloud-github-action@master
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      #   with:
      #     args: >
      #       -Dsonar.projectKey=apintodesignco_ALEJO
      #       -Dsonar.organization=apintodesignco
      #       -Dsonar.sources=src,alejo
      #       -Dsonar.tests=tests
      #       -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
      #       -Dsonar.python.coverage.reportPaths=coverage.xml
