name: ALEJO Comprehensive Testing

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]
  # Allow manual triggering
  workflow_dispatch:
    inputs:
      test_type:
        description: 'Type of tests to run'
        required: false
        default: 'all'
        type: choice
        options:
          - all
          - unit
          - integration
          - e2e
          - gesture
          - security
          - performance
          - quality

jobs:
  comprehensive-tests:
    name: Comprehensive Tests
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Run comprehensive tests
      run: |
        # Get the test type from input or default to 'all'
        TEST_TYPE="${{ github.event.inputs.test_type || 'all' }}"
        
        # Run the appropriate tests based on the test type
        if [ "$TEST_TYPE" = "security" ]; then
          python validate_security.py --ci --integration --json
        elif [ "$TEST_TYPE" = "gesture" ]; then
          python run_comprehensive_tests.py --gesture --ci --report
        else
          # Run all or specified test type
          python run_comprehensive_tests.py --"$TEST_TYPE" --ci --report
        fi
      
    - name: Archive test reports
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-reports
        path: |
          test_reports/
          coverage/
        retention-days: 14
