name: ALEJO Documentation

on:
  push:
    branches: [ main, develop ]
    paths:
      - '**.md'
      - 'docs/**'
      - 'src/**/*.js'
      - 'alejo/**/*.py'
  workflow_dispatch:

jobs:
  js-docs:
    name: Generate JavaScript Documentation
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: |
          npm ci
          npm install -g jsdoc
          
      - name: Generate JSDoc documentation
        run: jsdoc -c jsdoc.json
        
      - name: Upload JS documentation
        uses: actions/upload-artifact@v3
        with:
          name: js-documentation
          path: docs/js
          retention-days: 7
          
      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          destination_dir: js-docs
          
  python-docs:
    name: Generate Python Documentation
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sphinx sphinx_rtd_theme
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          
      - name: Generate Sphinx documentation
        run: |
          cd docs
          sphinx-build -M html . _build
          
      - name: Upload Python documentation
        uses: actions/upload-artifact@v3
        with:
          name: python-documentation
          path: docs/_build/html
          retention-days: 7
          
      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build/html
          destination_dir: py-docs
