name: Vision System Tests

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'src/personalization/vision/**'
      - 'test/personalization/vision/**'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'src/personalization/vision/**'
      - 'test/personalization/vision/**'
  # Allow manual triggering
  workflow_dispatch:

jobs:
  test:
    name: Run Vision System Tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Download face-api.js models
        run: |
          mkdir -p public/models
          curl -L https://github.com/vladmandic/face-api/archive/refs/tags/1.7.2.tar.gz | tar xz
          cp -r face-api-1.7.2/model/* public/models/
      
      - name: Run vision system tests
        run: npm test -- --dir=test/personalization/vision
      
      - name: Upload test coverage
        uses: codecov/codecov-action@v3
        with:
          directory: ./coverage/
          flags: vision-system
          name: vision-system-coverage
      
      - name: Generate test report
        if: always()
        run: npm run test:report
      
      - name: Upload test report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: vision-test-report
          path: test-report/
          retention-days: 7
